services:
  - type: web
    name: focusguard-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      # Install system dependencies for BERT and ML libraries
      apt-get update && apt-get install -y \
        build-essential \
        gcc \
        g++ \
        python3-dev \
        git \
        curl \
        wget \
        rustc \
        cargo
      
      # Upgrade pip and build tools
      pip install --upgrade pip setuptools wheel build
      
      # Set environment variables for optimized builds
      export BLIS_ARCH="x86_64"
      export NPY_NUM_BUILD_JOBS=1
      export TORCH_CUDA_ARCH_LIST="3.5;5.0;6.0;7.0;7.5;8.0;8.6"
      export CUDA_HOME="/usr/local/cuda"
      export CARGO_HOME="/tmp/cargo"
      export RUSTUP_HOME="/tmp/rustup"
      
      # Install pydantic v1 (no Rust compilation needed)
      pip install --no-cache-dir pydantic==1.10.13
      
      # Install numpy and scikit-learn with pre-compiled wheels
      pip install --no-cache-dir --only-binary=all numpy==1.26.4
      pip install --no-cache-dir --only-binary=all scikit-learn==1.4.0
      
      # Install PyTorch CPU version
      pip install torch==2.5.0+cpu torchvision==0.20.0+cpu torchaudio==2.5.0+cpu --index-url https://download.pytorch.org/whl/cpu
      
      # Install other requirements
      pip install --no-cache-dir --prefer-binary -r requirements.txt
      
      # Basic setup complete
      echo "✅ Basic dependencies installed successfully"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.13.4"
      - key: PORT
        value: "8000"
      - key: TRANSFORMERS_CACHE
        value: "/tmp/transformers_cache"
      - key: HF_HOME
        value: "/tmp/huggingface"
      - key: TORCH_HOME
        value: "/tmp/torch"
      - key: BERT_DISABLE_GPU
        value: "true"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - focusguard-app/**
