services:
  - type: web
    name: focusguard-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y build-essential gcc g++ python3-dev
      # Upgrade pip and build tools
      pip install --upgrade pip setuptools wheel
      # Set environment variables to avoid compilation issues
      export BLIS_ARCH="x86_64"
      export NPY_NUM_BUILD_JOBS=1
      # Install packages with optimizations for faster builds
      pip install --no-cache-dir --prefer-binary -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PORT
        value: "8000"
