services:
  - type: web
    name: focusguard-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      # Install system dependencies for BERT and ML libraries
      apt-get update && apt-get install -y \
        build-essential \
        gcc \
        g++ \
        python3-dev \
        git \
        curl \
        wget
      
      # Upgrade pip and build tools
      pip install --upgrade pip setuptools wheel
      
      # Set environment variables for optimized builds
      export BLIS_ARCH="x86_64"
      export NPY_NUM_BUILD_JOBS=1
      export TORCH_CUDA_ARCH_LIST="3.5;5.0;6.0;7.0;7.5;8.0;8.6"
      export CUDA_HOME="/usr/local/cuda"
      
      # Install PyTorch CPU version (more compatible with Render)
      pip install torch==2.1.0+cpu torchvision==0.16.0+cpu torchaudio==2.1.0+cpu --index-url https://download.pytorch.org/whl/cpu
      
      # Install other requirements
      pip install --no-cache-dir --prefer-binary -r requirements.txt
      
      # Download BERT models during build (optional, will download on first run if not done here)
      python -c "
      try:
          from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification
          from sentence_transformers import SentenceTransformer
          print('✅ BERT models will be downloaded on first run')
      except Exception as e:
          print(f'⚠️ BERT setup: {e}')
      "
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PORT
        value: "8000"
      - key: TRANSFORMERS_CACHE
        value: "/tmp/transformers_cache"
      - key: HF_HOME
        value: "/tmp/huggingface"
      - key: TORCH_HOME
        value: "/tmp/torch"
      - key: BERT_DISABLE_GPU
        value: "true"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - focusguard-app/**
