services:
  - type: web
    name: focusguard-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential \
      && pip install -r requirements.txt \
      && python -m spacy download en_core_web_sm
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
